# Włączenie ekranu OLED (ZMK sam pobierze odpowiedni sterownik SSD1306 dla nice!nano)
CONFIG_ZMK_DISPLAY=y

# Włączenie obsługi enkoderów
#CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Dodatkowe opcje oszczędzania energii dla Bluetooth (zalecane)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
